// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAPIKeys():Promise<main.APIKeys>;

export function GetDataDir():Promise<string>;

export function GetFiles():Promise<Array<main.File>>;

export function SaveAPIKeys(arg1:main.APIKeys):Promise<void>;

export function SaveFiles(arg1:Array<main.File>):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
