// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIKeys() {
  return window['go']['main']['App']['GetAPIKeys']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function SaveAPIKeys(arg1) {
  return window['go']['main']['App']['SaveAPIKeys'](arg1);
}

export function SaveFiles(arg1) {
  return window['go']['main']['App']['SaveFiles'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}
